default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] || '' %> # 記述箇所
  # socket: /tmp/mysql.sock
  host: <%= ENV['MYSQL_HOST'] || 'db' %> # 記述箇所
  port: 3306

development:
  <<: *default
  # adapter: mysql2
  # username: root
  # password:
  # host: localhost
  database: asobiba_development

test:
  <<: *default
  # adapter: mysql2
  # username: root
  # password:
  # host: localhost
  database: asobiba_test

production:
  <<: *default
  adapter: mysql2
  port: 3306
  database: asobiba_production
  username: appuser
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock